### ISSUE TITLE
Set-LoggingCustomTarget throws error

### ISSUE THREAD

**Issue by jeremymcgee73** [EsOsO/Logging#81]
When setting a custom logging target, I get the following error. I am using PowerShell 5.1 and version 4.2.13. I'm pretty certain that the event will be removed once the runspace is removed anyways. I don't think it needs to be unregistered from my local testing.

This is the script I used to test. [Test-Logging](https://github.com/jeremymcgee73/PowershellScripts/tree/master/Test-Logging).

 `Set-LoggingCustomTarget : Cannot bind argument to parameter 'SubscriptionId' because it is null.`. 

Thanks so much for your help!

**Comment by Tadas** [comment]
I think the error happens here https://github.com/EsOsO/Logging/blob/80f6ff5b3c321f3b76fa5911e60a47db36b7bb3b/Logging/private/Stop-LoggingManager.ps1#L11

#82 reintroduces `$Script:LoggingRunspace.EngineEvent` so it should fix this issue

**Comment by jeremymcgee73** [comment]
I'm still having an issue that's very intermittent. Sometimes the custom target loads, sometimes it does not. I'll try to take another look tomorrow.

**Comment by Tadas** [comment]
@jeremymcgee73 I believe both of your issues should be resolved by #92 and #100
